---

# Copy this to config.yml and edit accordingly

# List of subjects
subjects:
  gym:
    name: Gym

  mat:
    name: Maths

  fr:
    name: French

  chem:
    name: Chemistry

  phys:
    name: Physics

  world:
    name: Contemporary world

  info:
    name: Info

  dram:
    name: drama

  ecr:
    name: ECR

  en:
    name: English

  mus:
    name: Music

# the cycle is postponed on these days
# make sure to format dates exactly like this (otherwise it won't be parsed as a date!)
vacation_days:
  - single: 2023-09-04

  - single: 2023-10-09

  - start:  2023-10-30
    end:    2023-11-03

  - single: 2023-11-17

  - single: 2023-11-24

  - start:  2023-12-25
    end:    2024-01-08

  - start:  2024-01-29
    end:    2024-02-05

  - start:  2024-03-01
    end:    2024-03-10

  - start:  2024-03-29
    end:    2024-04-05

  - single: 2024-04-19

  - start:  2024-05-17
    end:    2024-05-21

start_date: 2023-08-25
end_date:   2024-06-06

schedule_slots:
  - start: '08:45'
    end:   '09:30'
  - start: '09:30'
    end:   '10:15'

  - start: '10:30'
    end:   '11:15'
  - start: '11:15'
    end:   '12:00'

  - start: '13:00'
    end:   '13:45'
  - start: '13:45'
    end:   '14:30'

  - start: '14:45'
    end:   '15:45'

# short classes are 1 timeslot, otherwise 2
schedule:
  1:
    classes:
      - id: fr
        loc: 360
      - id: mat
        loc: 362
      - id: phys
        loc: 364
        short: true
      - id: ecr
        loc: 364
        short: true
      - id: chem
        loc: 364
  2:
    classes:
      - id: en
        loc: 368
      - id: world
        loc: 368
      - id: chem
        loc: 362
      - id: info
        loc: Info room
  3:
    classes:
      - id: gym
        loc: Gym 4
      - id: chem
        loc: 362
      - id: dram
        loc: Drama room
      - id: mat
        loc: 362
  4:
    classes:
      - id: mat
        loc: 362
      - id: phys
        loc: 364
      - id: en
        loc: 368
      - id: chem
        loc: 364
  5:
    classes:
      - id: fr
        loc: 360
      - id: mus
        loc: Music room
      - id: mat
        loc: 362
      - id: fr
        loc: 360
  6:
    classes:
      - id: phys
        loc: 364
      - id: fr
        loc: 360
      - id: world
        loc: 362
      - id: world
        loc: 362
